# Author Detials
title:            Untitled
tagline:          Untitled Jekyll Theme
url:              /untitled/
description:      This is a barebones Jekyll theme to build a portfolio and is easy to customize.
twitter_username:
github_username:

navbar_icon:      /images/untitled-icon.svg # 60px/60px

# Build settings
markdown:         kramdown

# Permalinks
permalink: /:categories/:title/

exclude:          [".gitignore", "bower.json", "gruntfile.js", "package.json", "node_modules", "app", "README.md", "_less", "json"]